---
# Unattended security updates are enabled by default on Ubuntu  
# However, on cloud VMs, this feature can cause issues with a dpkg lock conflict:
# It is therefore currently disabled on SURF Research Cloud
# This Playbook runs a script that waits until cloud-init is done, then enable unattended upgrades

- name: Enable unattended security upgrades on Ubuntu
  hosts: localhost
  gather_facts: true

  tasks:
    - name: End play if not on Ubuntu
      meta: end_play
      when: ansible_distribution != "Ubuntu"
    
    - name: Get cloud-init status
      command: cloud-init status
      register: cloud_init_status

    - name: Debug
      ansible.builtin.debug:
        var: cloud_init_status.stdout

    - name: Include the role
      include_role:
        name: unattended_upgrades

    # Create a dependency conflict!
    # - name: Run updates immediately
    #   shell: nohup systemctl start apt-daily-upgrade < /dev/null >/dev/null 2>&1 &

    # - name: Install big package for testing
    #   package:
    #     name: gnome
    #     state: present