---
# Unattended security updates are enabled by default on Ubuntu  
# However, on cloud VMs, this feature can cause issues with a dpkg lock conflict:
# It is therefore currently disabled on SURF Research Cloud
# This Playbook runs a script that waits until cloud-init is done, then enable unattended upgrades

- name: Enable unattended security upgrades on Ubuntu
  hosts: all
  gather_facts: true

  roles:
    - unattended_upgrades